Repository openshift/online-analytics, pull requests merged in 2018-03, with the labels that each got.

#10 Check status after deploying
  ansible/roles/oso_analytics/tasks/main.yml
Labels: size/M

#11 ansible use osoan_name throughout
  ansible/roles/oso_analytics/defaults/main.yml
  ansible/roles/oso_analytics/tasks/main.yml
  ansible/roles/oso_analytics/templates/analytics-template.yaml.j2
Labels: lgtm, size/S

#12 remove template file when running uninstall
  ansible/roles/oso_analytics/tasks/main.yml
  ansible/roles/oso_analytics/tasks/uninstall.yml
Labels: lgtm, size/XS

#13 ansible ensure template directory exists
  ansible/roles/oso_analytics/defaults/main.yml
  ansible/roles/oso_analytics/tasks/main.yml
Labels: size/XS
